---
title: "final"
author: "xinran"
date: "11/6/2019"
output: github_document
---
# 1. The group members (names and UNIs)
Anran Shao(as5685)
Jun Yin(jy2965)
Xinran Luo(xl2851)
Roxana Yixuan Yan(yy2912)
Tianna Ouyang(to2345)

# 2. The tentative project title




# 3. The motivation for this project

Squirrels have always served as a needed source of entertainment in Central Park. Other rodent's population has been well traced and documented by human, but not always Squirrels. However, the necessity of mapping the total population of squirrels in Central Park is observed as it depicts this community's size and growth, which is highly related to the evaluation of this community's functioning as a source of entertainment, as well as their potential of harboring and delivering pathogens to human.

In this project, we use The Squirrel Census data from NYC Open Data host, which focuses on Eastern gray species specifically. For this project, we aim at depicting a full picture of the current squirrels commmunity in Central Park, with regards to their demographics statistics as well as their living status. We also intend to assess their performance and activity of Squirrels in Central Park, by evaluating their interactions with humans.

We believe this project can provide evidence-based information of the Central Park Squirrel community, as well as contribute to the aspect of the evaluation and regulation of the Squirrel team. This project also have the potential in providing further management insights for the planning and designing aspect of the Central Park. 







# 4. The intended final products

We expect to create a website contains 4 main aspects: 
1) Background and introduction: briefly introduce our motivation and our dataset as well as our results. Maybe this part will include some pictures and videos of squirrels to make our website more enjoyable. 
2) Descriptive statistics: using tables and plots to describle the distribution of squirrels and their activities in central park. For example, their frequency of appearance, the most popular place for squirrels. 
3) Correlation chart & predictive model: Before building any models, we would like to see the correlations between different variables in our dataset. Then we could choose what variables we would use for building models based on the plot we generated.
By using squirrels performance and activities as predictor, we intend to build a predictive model to assess the interaction between squirrels and human.
4) Conclusion and comparison: After we calculate our coefficients in our model, we will get some conclusions. By comparing other people's findings with our results, we would like to plan the next step analysis.
# 5. The anticipated data sources



# 6. The planned analyses / visualizations / coding challenges


# 7. The planned timeline
